# Site settings
title: Dr.Yami
email: cuongnt.hn@gmail.com
description: "Dr.Yami's Personal Homepage, includes portfolio and blog."
baseurl: ""
url: "http://yamiworld.com"

# Build settings
markdown: kramdown
permalink: /blog/:categories/:title/
